version: "3.9"


x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "auth-service-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth_service_db"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_USER: "lucas"

x-rabbitmq-variables: &x-rabbitmq-variables
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "auth-service"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  HTTP_USE_PREFORK_MODE: "false"
  # Logger
  LOG_LEVEL: "debug"
  # PG
  PG_POOL_MAX: "2"
  PG_URL: "postgres://lucas:123456@auth-service-db:5432/auth_service_db"
  # gRPC
  GRPC_PORT: "8081"
  # RMQ
  RMQ_RPC_SERVER: "rpc_server"
  RMQ_RPC_CLIENT: "rpc_client"
  RMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"


services:
  auth-service-db:
    container_name: auth-service-db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        aliases:
          - auth-service-db.lvh.me

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1-management
    environment:
      <<: *x-rabbitmq-variables
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      app_network:
        aliases:
          - rabbitmq.lvh.me

  auth-service:
    container_name: auth-service
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # gRPC
    depends_on:
      - auth-service-db
      - rabbitmq
    networks:
      app_network:
        aliases:
          - app.lvh.me

networks:
  app_network:
    external: false


volumes:
  postgres_db_data:
  rabbitmq_data:
